version: "1.0.0"
services:
   mongodb:
      image: "mongo"
      container_name: "mongodb"
      ports:
       - "27017:27017"
      volumes:
       - "mongodb_database:/data/db"
   backend:
      image: "backend"
      container_name: "backend"
      depends_on:
       - "mongodb"
      ports:
       - "3000:3000"
      environment:
       MONGO_URL: "mongodb://mongodb:27017/database"

volumes:
  mongodb_database:


        
